import esphome.codegen as cg
from esphome.components import number
from esphome.const import (
    CONF_MAX_VALUE,
    CONF_MIN_VALUE,
    CONF_STEP,
    DEVICE_CLASS_DURATION,
    DEVICE_CLASS_TIMESTAMP,
    DEVICE_CLASS_TEMPERATURE,
    ENTITY_CATEGORY_CONFIG,
    UNIT_CELSIUS,
    UNIT_EMPTY,
    UNIT_HOUR,
    UNIT_MILLISECOND,
    UNIT_MINUTE,
    UNIT_PERCENT,
    UNIT_SECOND,
)

from . import (
    CONF_EKHHE_ID,
    DaikinEkhhe,
    daikin_ekhhe_ns,
)
from .const import *
from .schema_helpers import (
    NumberSchemaSpec,
    number_schema,
    optional_schema_entries,
    platform_schema,
)

DaikinEkhheNumber = daikin_ekhhe_ns.class_(
    "DaikinEkhheNumber", number.Number, cg.Component
)

NUMBER_SPECS = [
    NumberSchemaSpec(
        P1_LOW_WAT_PROBE_HYST,
        min_value=2,
        max_value=15,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P2_HEAT_ON_DELAY,
        min_value=0,
        max_value=90,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P3_ANTL_SET_T,
        min_value=50,
        max_value=75,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P4_ANTL_DURATION,
        min_value=0,
        max_value=90,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P7_DEFROST_CYCLE_DELAY,
        min_value=30,
        max_value=90,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P8_DEFR_START_THRES,
        min_value=-30,
        max_value=0,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P9_DEFR_STOP_THRES,
        min_value=2,
        max_value=30,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P10_DEFR_MAX_DURATION,
        min_value=3,
        max_value=12,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P17_HP_START_DELAY_DIG1,
        min_value=10,
        max_value=60,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P18_LOW_WAT_T_DIG1,
        min_value=20,
        max_value=60,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P19_LOW_WAT_T_HYST,
        min_value=5,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P20_SOL_DRAIN_THRES,
        min_value=100,
        max_value=150,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P21_LOW_WAT_T_HP_STOP,
        min_value=30,
        max_value=70,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P22_UP_WAT_T_EH_STOP,
        min_value=30,
        max_value=80,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P25_UP_WAT_T_OFFSET,
        min_value=-25,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P26_LOW_WAT_T_OFFSET,
        min_value=-25,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P27_INLET_T_OFFSET,
        min_value=-25,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P28_DEFR_T_OFFSET,
        min_value=-25,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P29_ANTL_START_HR,
        min_value=0,
        max_value=23,
        device_class=DEVICE_CLASS_TIMESTAMP,
        unit_of_measurement=UNIT_HOUR,
    ),
    NumberSchemaSpec(
        P30_UP_WAT_T_EH_HYST,
        min_value=2,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P31_HP_PERIOD_AUTO,
        min_value=10,
        max_value=80,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P32_EH_AUTO_TRES,
        min_value=2,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P34_EEV_SH_PERIOD,
        min_value=20,
        max_value=90,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_SECOND,
    ),
    NumberSchemaSpec(
        P35_EEV_SH_SETPOINT,
        min_value=-8,
        max_value=15,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P36_EEV_DSH_SETPOINT,
        min_value=60,
        max_value=110,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(P37_EEV_STEP_DEFR, min_value=5, max_value=50),
    NumberSchemaSpec(P38_EEV_MIN_STEP_AUTO, min_value=3, max_value=45),
    NumberSchemaSpec(P40_EEV_INIT_STEP, min_value=5, max_value=50),
    NumberSchemaSpec(
        P41_AKP1_THRES,
        min_value=-10,
        max_value=10,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P42_AKP2_THRES,
        min_value=-10,
        max_value=10,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P43_AKP3_THRES,
        min_value=-10,
        max_value=10,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(P44_EEV_KP1_GAIN, min_value=-10, max_value=10),
    NumberSchemaSpec(P45_EEV_KP2_GAIN, min_value=-10, max_value=10),
    NumberSchemaSpec(P46_EEV_KP3_GAIN, min_value=-10, max_value=10),
    NumberSchemaSpec(
        P47_MAX_INLET_T_HP,
        min_value=38,
        max_value=43,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P48_MIN_INLET_T_HP,
        min_value=-10,
        max_value=10,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P49_EVA_INLET_THRES,
        min_value=10,
        max_value=40,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P50_ANTIFREEZE_SET,
        min_value=0,
        max_value=15,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P51_EVA_HIGH_SET,
        min_value=60,
        max_value=100,
        unit_of_measurement=UNIT_PERCENT,
    ),
    NumberSchemaSpec(
        P52_EVA_LOW_SET,
        min_value=10,
        max_value=60,
        unit_of_measurement=UNIT_PERCENT,
    ),
    NumberSchemaSpec(
        P53_EVA_FAN_DEFR_SPEED,
        min_value=0,
        max_value=100,
        unit_of_measurement=UNIT_PERCENT,
    ),
    NumberSchemaSpec(
        P54_LOW_PRESS_BYPASS,
        min_value=1,
        max_value=240,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MINUTE,
    ),
    NumberSchemaSpec(
        P55_EVA_BAND1_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P56_EVA_MAX_ACT_DELTA,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P57_EVA_MAX_DEACT_DELTA,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P59_EVA_FAN_OFF_SPEED,
        min_value=0,
        max_value=100,
        unit_of_measurement=UNIT_PERCENT,
    ),
    NumberSchemaSpec(
        P60_EVA_AIR_DELTA1,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P61_EVA_AIR_DELTA2,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P62_EVA_AIR_DELTA3,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P63_EVA_AIR_DELTA4,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P64_EVA_AIR_DELTA5,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P65_EVA_AIR_DELTA6,
        min_value=1,
        max_value=25,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P66_EVA_BAND2_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P67_EVA_BAND3_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P68_EVA_BAND4_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P69_EVA_BAND5_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P70_EVA_BAND6_PROP,
        min_value=1,
        max_value=20,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        P71_EC_FAN_SILENT_RED,
        min_value=0,
        max_value=40,
        unit_of_measurement=UNIT_PERCENT,
    ),
    NumberSchemaSpec(
        P72_EC_FAN_REG_GAIN,
        min_value=1,
        max_value=100,
        unit_of_measurement=UNIT_EMPTY,
    ),
    NumberSchemaSpec(
        AUTO_T_TEMPERATURE,
        min_value=43,
        max_value=62,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        ECO_T_TEMPERATURE,
        min_value=43,
        max_value=62,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        BOOST_T_TEMPERATURE,
        min_value=43,
        max_value=75,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        ELECTRIC_T_TEMPERATURE,
        min_value=43,
        max_value=75,
        device_class=DEVICE_CLASS_TEMPERATURE,
        unit_of_measurement=UNIT_CELSIUS,
    ),
    NumberSchemaSpec(
        VAC_DAYS,
        min_value=1,
        max_value=30,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_EMPTY,
    ),
    NumberSchemaSpec(
        TX_SEND_CALIBRATION,
        min_value=0,
        max_value=250,
        device_class=DEVICE_CLASS_DURATION,
        unit_of_measurement=UNIT_MILLISECOND,
        entity_category=ENTITY_CATEGORY_CONFIG,
    ),
    NumberSchemaSpec(
        TIME_BAND_START_HOUR,
        min_value=0,
        max_value=23,
        unit_of_measurement=UNIT_HOUR,
        entity_category=ENTITY_CATEGORY_CONFIG,
    ),
    NumberSchemaSpec(
        TIME_BAND_START_MINUTE,
        min_value=0,
        max_value=59,
        unit_of_measurement=UNIT_MINUTE,
        entity_category=ENTITY_CATEGORY_CONFIG,
    ),
    NumberSchemaSpec(
        TIME_BAND_END_HOUR,
        min_value=0,
        max_value=23,
        unit_of_measurement=UNIT_HOUR,
        entity_category=ENTITY_CATEGORY_CONFIG,
    ),
    NumberSchemaSpec(
        TIME_BAND_END_MINUTE,
        min_value=0,
        max_value=59,
        unit_of_measurement=UNIT_MINUTE,
        entity_category=ENTITY_CATEGORY_CONFIG,
    ),
]

TYPES = [spec.key for spec in NUMBER_SPECS]

CONFIG_SCHEMA = platform_schema(
    CONF_EKHHE_ID,
    DaikinEkhhe,
    optional_schema_entries(
        NUMBER_SPECS, lambda spec: number_schema(DaikinEkhheNumber, spec)
    ),
)


async def setup_conf(config, key, hub):
    if key in config:
        conf = config[key]

        num = await number.new_number(
            conf,
            min_value=conf[CONF_MIN_VALUE],
            max_value=conf[CONF_MAX_VALUE],
            step=conf[CONF_STEP],
        )
        cg.add(getattr(hub, "register_number")(key, num))
        cg.add(num.set_parent(hub))
        cg.add(num.set_internal_id(key))


async def to_code(config):
    hub = await cg.get_variable(config[CONF_EKHHE_ID])
    for key in TYPES:
        await setup_conf(config, key, hub)
